### ISSUE TITLE
lemminx-alpine server not found

### ISSUE THREAD

**Issue by cirolosapio** [redhat-developer/vscode-xml#1015]
the alpine version is present
![image](https://github.com/redhat-developer/vscode-xml/assets/33943143/b56dbb44-d156-4b77-8c46-d2c6e02ee891)

but the extension is looking for the linux one
```
[Error - 11:49:40 AM] XML Support client: couldn't create connection to server.
Launching server using command /home/vscode/.vscode-server-insiders/extensions/redhat.vscode-xml-0.27.2024053103-alpine-x64/server/lemminx-linux failed. Error: spawn /home/vscode/.vscode-server-insiders/extensions/redhat.vscode-xml-0.27.2024053103-alpine-x64/server/lemminx-linux ENOENT
```

**Comment by rgrunber** [comment]
I think the problem is around https://github.com/redhat-developer/vscode-xml/pull/991/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R131 right ? Instead of naming the binary `lemminx-alpine`, we just need to name it `lemminx-linux`, although it does get packaged into the alpine vsix. We also need to make sure it doesn't clash with the non-static `lemminx-linux` binary that is destined for the linux vsix.

**Comment by cirolosapio** [comment]
but the binaries are different because they are built with different flags
I think the extension should look for the correct os, see #1016

**Comment by rgrunber** [comment]
Initially I didn't want to have the runtime code change, as I felt it was better to just modify how we package it. After all, we can definitely have 2 files (lemminx-linux) exist in separate packages. The problem is these files can exist independently and we do sort of encourage users to download them separately at https://github.com/redhat-developer/vscode-xml/releases/tag/0.27.1 . If a user has some file named `lemminx-linux` it becomes harder to figure out immediately which it is (without asking them to do an ldd). Also might complicate the checksum situation.

So yeah, I think your approach is the right one.
