### ISSUE TITLE
XML is not offered as a formatter

### ISSUE THREAD

**Issue by xLexip** [redhat-developer/vscode-xml#1023]
Hey there,

I've installed the redhat xml extension in my vscode.
![image](https://github.com/user-attachments/assets/6c7c581d-1101-467a-861f-d229bd4b9991)

Unfortunately, XML is not offered as a formatter for .xml files for me:
![image](https://github.com/user-attachments/assets/4f7a0c0a-9933-42f8-b1fa-3188ff6d0d76)

Restarting vscode or setting it as a formatter in the settings.json does not help.
`    "[xml]": {
        "editor.defaultFormatter": "redhat.vscode-xml"
    },`

VS code version: 1.92.2 on Windows11

**Comment by angelozerr** [comment]
If you wrtite an invalid XML content, do you see some errors?

**Comment by fbricon** [comment]
If XML is not listed, it might be because the extension failed to start. Can you see anything in the vscode logs? Can you see XML Support in the Output view?
<img width="622" alt="Screenshot 2024-08-29 at 11 24 01" src="https://github.com/user-attachments/assets/96aeec70-a712-48ea-9d3c-ae3792e13a7b">

**Comment by xLexip** [comment]
Thank you both. I couldn't find any relevant extension logs and it turned out there was just a corrupt file association in the settings.json made by another extension. 
Thanks for your help and sorry for wasting your time. :]
