### ISSUE TITLE
Consume released lsp4xml build when performing a release

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-xml#105]
right now, the vscode-xml release process rebuilds the whole lsp4xml package from master, it should instead download the released version, without building it and simply embed it.

**Comment by rgrunber** [comment]
Closing for now due to infrastructure limitations. We can't build the binaries on Eclipse infra.

Current situation is that the universal (Java) language server is published at https://download.eclipse.org/lemminx/releases/ from https://ci.eclipse.org/lemminx/job/lemminx-release/. However, we also generate a binaries (win/mac/linux) with `-Pnative` from the same build on separate infrastructure. As a result it makes sense to just rebuild and ensure the binary and Java artifacts come from the same build.
