### ISSUE TITLE
vscode not reloading and revalidating XML/XSD files modified outside itself

### ISSUE THREAD

**Issue by stodge** [redhat-developer/vscode-xml#131]
Issue Type: <b>Bug</b>

I am using vscode to validate XML and XSDs. I have a script in a docker container that modifes the XML and XSDs. So the script writes to the volume and vscode loads the files from the volume (mounted into the container from my local filesystem). When the script updates the XML and XSD files, vscode doesn't appear to always revalidate the XML and XSD files unless I manually modify them within vscode. Perhaps vscode doesn't recognise that the files were modified outside of its own environment?

Centos 7

Extension version: 0.5.1
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 3.10.0-957.10.1.el7.x86_64

**Comment by fbricon** [comment]
exactly. VS Code can only listen to file changes of folders that are open in it

**Comment by fbricon** [comment]
actually, if the folders containing the files are already opened in vscode, but modified by a 3rd party, it should send a change event to the XML language server, which should trigger validation. I'll let @NikolasKomonen or @angelozerr investigate in more details

**Comment by NikolasKomonen** [comment]
Investigating now

**Comment by fbricon** [comment]
@NikolasKomonen I don't remember lsp4xml configuring filewatchers, so that might be the issue

**Comment by NikolasKomonen** [comment]
@fbricon @stodge 

So what is happening is that when the XSD is changed externally from another editor, the text in VSCode changes and sends a `textDocument/didChange` command, but VSCode never 'saves' the document because it was saved in the other editor.

Because of this a `textDocument/didSave` command is never sent and the mechanism to re-validate the XML files is never triggered.

Maybe there is a way to detect this and force a save.

But as @stodge said, the quickest workaround for now is to add a space in the XSD, delete it, then save.

**Comment by fbricon** [comment]
with workspace/didChangeWatchedFiles, you could trigger a validation of opened xml files if a non-opened xsd has been modified

**Comment by stodge** [comment]
Thanks all.

**Comment by angelozerr** [comment]
This issue is the same than https://github.com/redhat-developer/vscode-xml/issues/132 which is fixed in 0.8.0
