### ISSUE TITLE
Formatting breaks attributes containing quotes

### ISSUE THREAD

**Issue by keccs** [redhat-developer/vscode-xml#182]
How to reproduce:
1. Use this document: `<hello attr='"' />`
2. Run the "Format document" command, with `xml.format.quotations` set to `doubleQuotes` (the default)

Symptoms:
The formatting produces the following invalid XML: `<hello attr=""" />`

Expected:
Formatting shouldn't change the type of quote used for an attribute if that produces invalid XML, that is if the attribute value contains the quote character.

**Comment by angelozerr** [comment]
I agree with you, but I think it's not a commons usecase.

**Comment by mcn-mark-gordon** [comment]
It also affects me. Due to the nature of the system I am developing stylesheets for I sometimes need to use double-quotes in attributes and sometimes need to use apostrophes in them.

It might not be common (I don't know), but it is certainly more than one person affected.

**Comment by brianary** [comment]
Whether or not it was a good design decision, [MuleSoft](https://www.mulesoft.com/) XML config files embed their DataWeave scripting language (which uses a lot of quotes) in attributes of their code. This indicates that an entire community is affected by this bug.

**Comment by fbricon** [comment]
@brianary can you please provide an example of such config file?

**Comment by brianary** [comment]
Here is one example element from a recent project:
```xml
				<set-payload
						value='#[output application/json
---
{
	"message": "Error while creating the record",
	"Message Text": error.muleMessage.typedValue default "Error Occured"
}]'
						doc:name="Set Payload"
						doc:id=" 6d5b1304-f21c-4e3f-83af-655d8b5293c6 " />
```
DataWeave is primarily a tool for mapping one object structure to another:
```xml
				<set-payload
						value='#[output application/json
---
{
	"Message": "Record created successfully",
	"ID": payload..id[0],
	"Type":payload..type_name[0],
	"Message Severity":payload..MsgSeverity default "No Error",
	"Message Text": payload..MsgText joinBy ";" default "Success"
}]'
						doc:name="Set Payload"
						doc:id=" 010e9893-7c8c-416d-bfa9-f4c48df6b6b4 " />

```

**Comment by angelozerr** [comment]
Thanks @brianary for your sample. But even if we fix this issue, I think the vscode-xml formatting will not be enough, because I suppose you want to format the attribute value which can contain JSON content. 

And I suppose you would like to have syntax coloration for this JSON content, no?

Those 2 issues (which are out of the scope of this issue) requires to provide some extension (particpant for format feature and TextMate injection for the synax coloration) which will not very simple to fix.

@fbricon @xorye perhaps we should fix this issue soon since more and more people complain with this quote problem?

**Comment by brianary** [comment]
What? No. It is DataWeave, not JSON (though it is similar), but in neither
case do I need syntax and highlighting support. Often (not primarily) that
code is manipulated via a GUI, but that formats the XML in ways that don't
diff well within git/GitHub. I just want to be able to use this extension
(the only one that does XML folding right) to format the XML more
predictably/consistently without it breaking our code. This is not a
slippery slope.

**Comment by angelozerr** [comment]
> I just want to be able to use this extension
(the only one that does XML folding right) to format the XML more
predictably/consistently without it breaking our code. 

nice :)

Ok now I understand more it's a blocking issue for you.

**Comment by brianary** [comment]
Thanks! I agree the choice of putting code in an attribute is weird enough
that it doesn't make much sense to try and add full language support.

**Comment by angelozerr** [comment]
To fix this issue, we should had a new enum `none` for `xml.format.quotations` which doesn't change the quote.

**Comment by fbricon** [comment]
I'd rather prefer `xml.format.quotations: existing`

**Comment by angelozerr** [comment]
> I'd rather prefer `xml.format.quotations: existing`

I suggested `none` to be consistent with `xml.format.EmptyElements : none` which means do nothing.

**Comment by fbricon** [comment]
then xml.format.emptyElements should use existing too ;-)

**Comment by angelozerr** [comment]
Ok!

**Comment by fbricon** [comment]
actually, I wonder if `ignore` would be a better fit for all

**Comment by angelozerr** [comment]
> actually, I wonder if ignore would be a better fit for all

I agree with that, I will do the changed

**Comment by angelozerr** [comment]
@fbricon after discussion with @xorye, I think `xml.format.quotation` should not exists. Today this settings is used 

 * for apply completion to generate attribute
 * for formatting

The most important feature is for completion apply, so I think we should have `xml.preferredQuotation` setting (instead of xml.format.quotation).

After that formatting will keep the existing quotation. Now if we want to force the quotation while formatting, I think we should introduce a new setting like `xml.format.usePreferedQuotation : true` which will replace the quotation, but if we do that, IMHO I think we should take care of the used quote in the attribute value (perhaps not replace the quote).

**Comment by fbricon** [comment]
@keccs you can now set `"xml.format.enforceQuoteStyle"="ignore"`
