### ISSUE TITLE
Installer doesn't prompt to install a JDK if none is found

### ISSUE THREAD

**Issue by Bob-Davis** [redhat-developer/vscode-xml#194]
I just installed the XML support extension on my macOS (10.14.6), and didn't get a prompt to install a JDK. When I followed up with installing the Java Extension Pack, I did get it though.  This is a fresh OS and I hadn't installed OpenJDK yet, so I should have gotten the prompt to download and install it.

Attached is an image of what I got with the Java Extension Pack installer, and would have expected to see when installing the XML extension.

<img width="512" alt="Screen Shot 2019-10-23 at 10 04 56 AM" src="https://user-images.githubusercontent.com/19437701/67413125-cf59d980-f57d-11e9-84d9-acd1a816449e.png">

**Comment by fbricon** [comment]
the same popup should show up not on install, but when the xml extension is activated, i.e when an xml document is opened

**Comment by Bob-Davis** [comment]
That might become frustrating for someone who just wants to edit a file quickly. Informing them again (even though it's in the docs as a requirement) might provide a better user experience.

**Comment by angelozerr** [comment]
> That might become frustrating for someone who just wants to edit a file quickly. 

I understand your frustration and I think no-java developer don't like our vscode-xml because they need to install Java and they prefer installing other XML extensions which don't require java.

I think vscode-xml is for user who wants advanced XML support like validation, completion based on XML Schema / DTD. If Java is not installed, it's a little boring to configure it, but after that you benefit with advanced XML support than other XML extensions (written in TypeScript) doesn't support.

vscode-xml consumes LSP4XML a language server written in Java. Why Java? Because LSP4XML is based on Xerces the Java library which manages advanced XML Schema / DTD validation. It doesn't exist in TypeScript the same library which provides the same features than Xerces.

> Informing them again (even though it's in the docs as a requirement) might provide a better user experience.

You mean that you wish to have the popup when you install the vscode-xml extension and not when you open a XML file?

**Comment by dsopko** [comment]
Simply boring to configure it? Here is a clue, I'm a non-java developer and I started attempting to install the extension at 3:40 PM, it's now 4:25 PM I've installed multiple versions of the JAVA SDK from Red Hat which I needed to hand over addresses, phone numbers, emails, and now I'm into multiple web searches as to why it still cant locate the Java SDK and now it appears the next step might be debugging source code. Is there really anything special in here that is worth my time?

**Comment by fbricon** [comment]
@dsopko did you set xml.java.home in your preferences?

**Comment by bluebrown** [comment]
> Simply boring to configure it? Here is a clue, I'm a non-java developer and I started attempting to install the extension at 3:40 PM, it's now 4:25 PM I've installed multiple versions of the JAVA SDK from Red Hat which I needed to hand over addresses, phone numbers, emails, and now I'm into multiple web searches as to why it still cant locate the Java SDK and now it appears the next step might be debugging source code. Is there really anything special in here that is worth my time?

To be frank, that sounds like you need to brush up on your general it skills. If you need advanced xml validation then you should be able to install a package and make its binary available to your system.

I came also here a bit frustrated, not because I can't install the jdk, but more because I don't want to. After reading the above explanation regarding Xerces, it makes totally sense though.

I think maybe a solution could be to offer a lighter version by default that allowed to opt into advanced features if the JDK is installed. I don't know if this would be doable because the code may be completely in java.

**Comment by fbricon** [comment]
@bluebrown we're working on providing an xml language server that doesn't require installing Java https://github.com/redhat-developer/vscode-xml/pull/316

**Comment by Lorenz-N** [comment]
Shouldn't this issue be closed already since you clearly noted at the README:

> NO LONGER REQUIRES JAVA! since v0.15.0

https://github.com/redhat-developer/vscode-xml#no-longer-requires-java-since-v0150

**Comment by angelozerr** [comment]
You are right @Lorenz-N, thanks for the update. 

Fixed with https://github.com/redhat-developer/vscode-xml/pull/316
