### ISSUE TITLE
Saving our Improvments Upstream ? :)

### ISSUE THREAD

**Issue by rwx-777** [redhat-developer/vscode-xml#200]
Hello there,

my name is Joshua I work for Atsec. We have made a few changes to your XML Language Support Plugin, from our Perspective we would say Improvements, as it is now easier to read the XML. This Format is similar to Oxygen, which we used before to edit XML Files. Feel free to have a look at it and come back to us with any improvments or ideas.

Here is our Repo we forked:
https://github.com/enxio/lsp4xml

Here you can see the changes we made to these files:
https://github.com/angelozerr/lsp4xml/compare/master...enxio:master#files_bucket

The Files we changed are as follows:
org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/services/XMLFormatter.java
org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/utils/StringUtils.java
org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/utils/XMLBuilder.java

Thank you for your time.

**Comment by angelozerr** [comment]
Hi Joshua ,

Thanks for your information. It's little hard to understand what your formatter does compare to our formatter. Could you explain more what is your goal? 

My quick understand is that you want to set some tag elements in the same line (b , bibref, color tags, etc )

As it's a custom configuration we could provide this capability with settings (you could set in the settings an array of tags like b, bibref, etc). Is it just that you try to do?

What do you think about this idea? 

IMHO I think you should contribute to lsp4xml instead of forking it because it will be hard for you to maintain your formatter with our future improvement like https://github.com/redhat-developer/vscode-xml/issues/196

**Comment by fbricon** [comment]
https://github.com/angelozerr/lsp4xml/compare/master...enxio:master seems a better link to use for comparisons

As @angelozerr said, please open a ticket or a PR on https://github.com/angelozerr/lsp4xml explaining your motivations (adding screenshots comparing formatting before/after your changes might help). And yes, looks like the list of tags to inline could be configurable.

**Comment by rwx-777** [comment]
@angelozerr @fbricon  Thank you very much for your fast reply. Yes, indeed we have implemented a Version, where we can set tag elements in the same line. It truly helps the readability of an XML File.
We would be very pleased if you could consider making this a custom configuaration as you already said. We like the idea of this very much. 
Thank you in advance for your time & efforts.

**Comment by angelozerr** [comment]
@rwx-777 if you wish this configurable feature please give us some usecases (create an another issue if you wish) and don't hesitate to create PR if you can.

**Comment by angelozerr** [comment]
@rwx-777 has created the issue at https://github.com/angelozerr/lsp4xml/issues/594
