### ISSUE TITLE
Support for exceptions in syntax, ant examples

### ISSUE THREAD

**Issue by TonyGravagno** [redhat-developer/vscode-xml#221]
I'm using this extension with ant build files. I've generated and published [Apache-Ant-Schema](https://github.com/TonyGravagno/apache-ant-schema) DTD and XSD, which is referenced by my build XML for validation.

Ant schema allows for some attributes to be a valid from a defined enumeration. For example, Boolean values can take values defined through an NMTOKEN as true, false, on, off, yes, or no. If we use something like `javac debug="nope"` we can expect an error, and yes, this extension flags it. Thanks!

In ant we can use runtime substitution variables. For example: `javac debug="${debugstate}"`. At runtime the value of debugstate should certainly be valid. But in the build XML the value hasn't been determined. This is valid ant code, but the extension flags this as a Problem. (Verified no error when disabling this extension.)

The 'fixes' offered only include changing the value to one from the enumeration, which is really cool when you get a literal value wrong. The 'fix' option that I'd like to see is to unflag a line as a problem. I don't want to ignore the problem or filter it out. This is not a problem in this scenario.

Ideally I'd like to unflag specific element/attribute/value sets. This will eliminate the same error for the same set wherever it is found, in any file, any workspace.

Another way to handle this is to be able to tell the extension that we're working with ant files, where any value that includes "${" should not get flagged as an invalid value. We don't want to exclude text beginning with ${, because valid values may not begin with that text.

[Here is another scenario](https://superuser.com/questions/1516963/dtd-or-xsd-for-xml-attribute-where-enumeration-list-includes-null) where it would help if we could tell the extension to be less rigid with its warnings.

If someone can point me to the relevant code, I could take a shot at doing an enhancement myself.

Thanks.

**Comment by angelozerr** [comment]
I understand the idea and if you want to have a robust support for and you must write a LSP4XML extension (in Java). Please read https://github.com/redhat-developer/vscode-xml#custom-xml-extensions

If you write a LSP4XML extension your XSD must be more lenient (remove xsd enumeration for instance?) but you could manage this completion at hand with your java LSP4XML completion participant.

> Ideally I'd like to unflag specific element/attribute/value sets. This will eliminate the same error for the same set wherever it is found, in any file, any workspace.

It will be very hard to do that since those errors comes from Xerces validator. If XSD have some rules, it must report it.

> If someone can point me to the relevant code, I could take a shot at doing an enhancement myself.

As I suggest you, you must write an LSP4XML. Starts reading  https://github.com/redhat-developer/vscode-xml#custom-xml-extensions and if you need some more info, please tell us.

**Comment by angelozerr** [comment]
@TonyGravagno have you tried to implement your own participant (completion, validation, etc) to manage your usecase?

**Comment by TonyGravagno** [comment]
I've been focused on business tasks and have not come back to this tooling challenge yet. Please forgive some time here until I can swing back around to this, look into LSP4XML, etc. Thank you VERY much for your follow-ups.

**Comment by angelozerr** [comment]
@TonyGravagno I close this issue since it's not an issue for vscode-xml or LemMinx (new name of LSP4XML since my project was moved to Eclipse.org) https://github.com/eclipse/lemminx

Please note there is a maven extension based on LemMinx which is developping
https://github.com/AObuchow/lsp4xml-extensions-maven 

If you need any help to develop LemMinx extension for ant, please create issues at https://github.com/eclipse/lemminx/issues
