### ISSUE TITLE
Allow support for variable and different file path notations in xml.FileAssociations

### ISSUE THREAD

**Issue by Marsfan** [redhat-developer/vscode-xml#307]
A number of things that are normally supported by configuration options in VS code JSON files do not seem to work when configuring xml.FileAssociations. 
Namely:
* Variable Substitution
* Windows-Style file paths. 

As an example, I have a test repository that has a schema in one folder, and an XML file in another folder. 

<details> 
<summary> Project Structure Photograph </summary>

![image](https://user-images.githubusercontent.com/9311953/89741366-510bec80-da56-11ea-93b3-ab313813f9f2.png)

</details>

```{
    "xml.fileAssociations": [{
            "systemId": "schema/schema.xsd",
            "pattern": "testFile/*.xml"
        }]
} 
```

This works as expected, XML files in the testFile folder are checked against the schema document. 

But if I instead refer to the files using the `${workspaceFolder}` variable built into VS code like this: 

```{
    "xml.fileAssociations": [{
            "systemId": "${workspaceFolder}/schema/schema.xsd",
            "pattern": "${workspaceFolder}/testFile/*.xml"
        }]
}
```

The files are not being checked against the schema, and I do not get any warnings. 

Furthermore, if I use windows style file path notation

``` {
    "xml.fileAssociations": [{
            "systemId": "schema\\schema.xsd",
            "pattern": "testFile\\*.xml"
        }]
}
```

I once again find that my XML files are not being checked against the schema file. 

Both of these should be supported when configuring settings for the extension. Variable substitution is important for configuring paths in global settings that will change for each workspace, and Windows file path support is necessary to maintain consistency with other options that might be set in the same file.

**Comment by angelozerr** [comment]
@fbricon what do you think about this idea?

**Comment by angelozerr** [comment]
@Marsfan do you see other variable substitution than `${workspaceFolder}` ?

**Comment by angelozerr** [comment]
I wonder if this variable substitution must be done on vscode-xml side or LemMinx (LS server) side. If we could manage workspaceFolder on LemMinx side it should be nice because all LSP client could benefit with that. Need to investigate if we can retrieve workspaceFolder on LemMinx server side.

It will depends too if we need to manage another variable substitution which could be specific to vscode. I'm waiting for answer of @Marsfan

**Comment by datho7561** [comment]
[Here is the list of all the supported variables](https://code.visualstudio.com/docs/editor/variables-reference).
* I won't implement the ones that only apply to multi-root projects, since vscode-xml doesn't work with multiroot projects as of yet.
* Currently investigating some of the other ones

**Comment by datho7561** [comment]
I think getting this working on the language server side could be helpful.

These appear to be the most helpful variables to me:
* `workspaceFolder`
* `fileBasenameNoExtension`
* `relativeFileDirname`

Another thing that I want to implement in this PR is using `.` in the file path to mean the same thing as `workspaceFolder`:
* Refer to a path relative to the opened folder in single root projects
* When/if we move to multiroot projects, we can take `.` to mean apply this rule to each workspace, using the root of each workspace as `workspaceFolder`

**Comment by angelozerr** [comment]
This issue is now supported, see docs at:

 * https://github.com/redhat-developer/vscode-xml/blob/master/docs/Validation.md#xml-file-association-with-xsd
 * https://github.com/redhat-developer/vscode-xml/blob/master/docs/Validation.md#xml-file-association-with-dtd

**Comment by mjohnson159** [comment]
It appears that environment variables are not supported in this, is that correct? My team has a bunch of different repos and each team have different environments (win, mac, linux) in which they work. So we all environment variables defined to point to the same repo, which is set individually. I was hoping to use the same variable we all use to reference in this so that every person doesn't have to manually change the `systemId` to match their own and instead could be the same

```
"systemId": "${env:REPO_LOC}/format.xsd"
```

I can open a new ticket for this request, if this is feasible.

**Comment by Wulgryn** [comment]
It's still not working 👎 :(
