### ISSUE TITLE
Respect http.proxy and http.proxyAuthorization settings

### ISSUE THREAD

**Issue by Yanpas** [redhat-developer/vscode-xml#416]
Proxy support doesn't work out of the box

**Comment by datho7561** [comment]
As far as I can tell, the client side code (which downloads the [XML language server](https://github.com/eclipse/lemminx)) works through the proxy if you set up `http.proxy` and set the [`http.proxySupport`](https://code.visualstudio.com/updates/v1_31#_network-proxy-support-for-extensions) setting to `override` or `on`. I'll take a look at the language server side next, which is probably where the problem is.

**Comment by angelozerr** [comment]
> Proxy support doesn't work out of the box

Could you explain more please what is your problem with proxy. I suspect that it's a download of DTD, XSD declared in a XML, is that?

**Comment by Yanpas** [comment]
Yes, schema downloading is the issue

**Comment by angelozerr** [comment]
Have you tried https://github.com/redhat-developer/vscode-xml/blob/354fc8c06757612e292a5a278b67353207324bd9/docs/Preferences.md#server-vm-arguments ?

**Comment by angelozerr** [comment]
Do you use binary modehttps://github.com/redhat-developer/vscode-xml/blob/354fc8c06757612e292a5a278b67353207324bd9/docs/Preferences.md#server-binary-mode or java mode (have you Java which is installed?)

**Comment by fbricon** [comment]
I guess we could automatically port the http proxy settings from vscode to their java equivalent, and inject them if the've not been set in vmargs already.
Do we also expose vmargs for the binary?

**Comment by datho7561** [comment]
Yes, we expose vmargs. I'll work on injecting the properties if they aren't already present in the user-created vmargs.

**Comment by datho7561** [comment]
This approach (injecting `http.proxyHost` and `http.proxyAuthorization` into the JVM arguments) doesn't work with binary. I'll have to look into passing these values to the language server some other way (maybe environment variables). For now, I'll open a draft PR with my work.
