### ISSUE TITLE
XLM extension does not recognize tags on Feb Visual Studio Code

### ISSUE THREAD

**Issue by okh-ibm** [redhat-developer/vscode-xml#419]
Issue Type: <b>Bug</b>

Open xml file, all tags are highlighted as errors.  This started with version 1.53.2

Extension version: 0.15.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (24.20GB free)|
|Process Argv|P:\\projects\\zadd1\\zadd1\\testgen\\gpro\\mywork1.code-workspace --crash-reporter-id 2d1dd3dd-25ec-4475-bb88-ef7498ee521b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by fbricon** [comment]
Can you add some sample files, enable xml.trace.server=verbose, attach logs from the XML Support output view?

**Comment by okh-ibm** [comment]
![Screenshot 2021-02-12 102827](https://user-images.githubusercontent.com/78971381/107794582-3c6a2300-6d1d-11eb-9c30-eed0bfca8423.png)

**Comment by okh-ibm** [comment]
I tried to attach the file, but it said that file type is not supported.
Have no idea how to set and collect logs you requested.

**Comment by okh-ibm** [comment]
![Screenshot 2021-02-12 102827](https://user-images.githubusercontent.com/78971381/107794861-94088e80-6d1d-11eb-97b8-92f9c9c5454c.png)

**Comment by fbricon** [comment]
- turn on `xml.trace.server` in the VSCode preferences
- restart vscode
- open file
- View -> Output -> XML Support (drop down menu top right)
- copy log and attach it here

**Comment by angelozerr** [comment]
> I tried to attach the file, but it said that file type is not supported.

Please copy paste in he issue:

 * the XML content
 * the DTD content

**Comment by angelozerr** [comment]
@fbricon just for your info,  we have a doc for that https://github.com/redhat-developer/vscode-xml/blob/master/docs/Troubleshooting.md#no-support-on-xml-file

**Comment by okh-ibm** [comment]
Do not see xml.trace.server

![Screenshot 2021-02-12 123031](https://user-images.githubusercontent.com/78971381/107807768-3d578080-6d2e-11eb-92db-e511c70349ff.png)

**Comment by okh-ibm** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE GPRODEF SYSTEM "gprodef.dtd">

<DEFINITION version="1.2.7">
  <prolog>
    <text name="Author" type="USERID" printToTest="TRUE" value="okh"/>
    <text name="Creation Date" type="DATE" value="2017/04/21"/>
    <text name="Creation Unix Time" type="DATE" value="1492786738"/>
    <text name="Reviewer" value="xxx"/>
  </prolog>

  <includeFile fileName="default.ih"/>
  <includeFile fileName="def.control.inc"/>

  <MACRO name="Main">
    <SEQUENCE>

      
      
      
      <I class="MyFeature"/>

    </SEQUENCE>
  </MACRO>

  <TEST>
    <varDecl initValue="&quot;vsxmlproblem.def,v 1.00 2021/02/12 okh &quot;" name="version" type="string"/>

    <SEQUENCE>

      <ASSIGN name="Size" value="Choose($Size)"/>

      <MACRO_CALL name="Prolog_Test"/>

      <CONCURRENT>
        <PROCESS id="DEFAULT">
         <MACRO_CALL name="Prolog_Process"/>
          <SEQUENCE>
            <MACRO_CALL name="Main"/>
          </SEQUENCE>
        </PROCESS>
      </CONCURRENT>

    </SEQUENCE>
  </TEST>


</DEFINITION>

**Comment by okh-ibm** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE GPRODEF SYSTEM "gprodef.dtd">

<DEFINITION version="1.2.7">
  <prolog>
    <text name="Author" type="USERID" printToTest="TRUE" value="okh"/>
    <text name="Creation Date" type="DATE" value="2017/04/21"/>
    <text name="Creation Unix Time" type="DATE" value="1492786738"/>
    <text name="Reviewer" value="xxx"/>
  </prolog>

  <includeFile fileName="default.ih"/>
  <includeFile fileName="def.control.inc"/>

  <MACRO name="Main">
    <SEQUENCE>

      
      
      
      <I class="MyFeature"/>

    </SEQUENCE>
  </MACRO>

  <TEST>
    <varDecl initValue="&quot;vsxmlproblem.def,v 1.00 2021/02/12 okh &quot;" name="version" type="string"/>

    <SEQUENCE>

      <ASSIGN name="Size" value="Choose($Size)"/>

      <MACRO_CALL name="Prolog_Test"/>

      <CONCURRENT>
        <PROCESS id="DEFAULT">
         <MACRO_CALL name="Prolog_Process"/>
          <SEQUENCE>
            <MACRO_CALL name="Main"/>
          </SEQUENCE>
        </PROCESS>
      </CONCURRENT>

    </SEQUENCE>
  </TEST>


</DEFINITION>

**Comment by fbricon** [comment]
Is vscode-xml actually installed/activated? If it was you should see XML settings

**Comment by angelozerr** [comment]
Thanks @okh-ibm for your XML sample. I have the same errors than you, but those errors exists with old version of vscode-xml (I tested with 0.12.0 8 month agoand we have the same errors).

Your problem is because your DTD association is wrong:

![image](https://user-images.githubusercontent.com/1932211/107812077-6ea47080-6d6f-11eb-944d-e679508f6af2.png)

and when prolog element must be validated, the DTD validator report an error as prolog definition cannot be find in the DTD (which doesn't exist).

![image](https://user-images.githubusercontent.com/1932211/107812191-9c89b500-6d6f-11eb-9b08-a60e85987076.png)

Are you sure that with an old version you did not this error. Could you install and old version of vscode-xml and check that please.

**Comment by okh-ibm** [comment]
Thanks.  I understand the comment about the dtd. I'll look them up in the documentation.

**Comment by angelozerr** [comment]
As your errors are normal (because your DTD file path is not valid) and as this behavior exists with old version of vscode-xml, 
I close this issue. 

I wonder if vscode-xml worked for you before the install of 0.15.0 because before 0.15.0 it required Java and perhaps you had not Java and vscode-xml didn't work (it's the reason why you had none errors).

But since 0.15.0, Java is not required that's why validation is working now and you see those errors.

Don't hesitate to create new issues if you find other troubles.
