### ISSUE TITLE
NodeJS 12 might not actually be used to build the extension

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-xml#428]
Given these lines in the Jenkinsfile:

```
def nodeHome = tool 'nodejs-12.13.1'
env.PATH="${env.PATH}:${nodeHome}/bin"
```

If an existing NodeJS is installed on the build agent, then it will be used instead of NodeJS 12, since it will be in the PATH before NodeJS 12.

**Comment by rgrunber** [comment]
Going to close this one for now. The appending to `PATH` seems pretty common for nodejs Jenkins jobs, and I suspect the reason we haven't run into issues is because it has never been made part of a default install. Projects may have different preferences for Node versions, so rather than trying to satisfy them all, the onus is placed on projects to provision the base system with their requirements.
