### ISSUE TITLE
Promote features of vscode-xml in docs

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-xml#475]
It should be nice to add a new page features in docs to highlight all features with litle demo of vscode-xml like 

* ~auto close~
* linked editing range un thé future
* ~hyperlink on end tag to jump to start tag~
* ~rename tag~
* codelens références inside xsd and dtd
* complétion based on xsd
* generate xsd from xml

I miss a lot of features and we should group features by topic like advanced editing support xsd support etc

I created this issue to start discussion and find the betterave organisation to promote vscode xml. The idea is to show that we support or will support some features that therme extension could support (i think for instance about rename tag extension which will be supportes when linked editing support will be supported)

**Comment by rgrunber** [comment]
I think this is a good start and we should do this.

Only thing I can say against such an approach is that I get the impression users very rarely read the welcome/new feature/help pages of extensions. I think more active approaches would probably be more successful. For example :

- If the issue is informing the user of useful settings that are not the default, keeping track of every property whose value is queried for various code paths (eg. `workspace.getConfiguration.get(..)`), and then if a user selects some option like "Improve My Workflow", which displays a list of the properties associated with their most common usage, which they should consider modifying.
- If we're talking about certain commands or keybindings, it would be cool (but sadly impractical) to have some kind local monitor/tracker that detects the inefficient behaviour and suggests the keybinding/command through a popup.
