### ISSUE TITLE
Reduce Telemetry volume for `server.document.open` 

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-xml#620]
`server.document.open` represents a massive amount of  telemetry events. We should try to aggregate the results instead and send them once a day (or at least once during the shutdown event).
We need to figure out how to aggregate the data without losing too much infprmation though.

**Comment by rgrunber** [comment]
This seems like the kind of problem that any consumer of https://github.com/redhat-developer/vscode-redhat-telemetry could run into. Is it possible to add another send method with some flag (set by the client) to indicate the event being sent occurs very frequently and should be aggregated (on shutdown), rather than directly reported ?

**Comment by fbricon** [comment]
Well it's tricky. The library would still need to know how to aggregate the data. Some properties would be grouped, some others would have to be ignored, this is all very dependent on usage

**Comment by rgrunber** [comment]
Looking at what's reported for `server.document.open` :
- `file.grammar.*` properties are only reported when true. We can convert them to integer, and aggregate each grammar type (none, doctype, xmlmodel, schemalocation, nonsschemalocation).

- `file.identifier` are `file.extension` are Strings and their values are not bounded. We could potentially just concatenate them into a single string but I'm guessing that really complicates analysis. Can the [`custom properties`](https://github.com/redhat-developer/vscode-redhat-telemetry/blob/main/src/services/reporter.ts#L35) field be nested ?
