### ISSUE TITLE
Renaming Tags with namespaces duplicates namespace

### ISSUE THREAD

**Issue by luechtdev** [redhat-developer/vscode-xml#621]
Version: 0.18.1

When renaming a namespaced XML-Tag - the namespace is duplicated.

**Steps to reproduce:**
1. Create a namespaced tag like `<ns:tagname>`
2. Put the cursor on top and press "F2" to rename
3. Change the name (for example `ns:tagname2`)

**Expected Result:**
Tag is renamed to `<ns:tagname2>`

**Actual result**
Tag is renamed to `<ns:ns:tagname2>`

**Comment by AlexXuChen** [comment]
This bug seems deeper than just `<ns:..>` tags, but actually persists on any tag containing `:`:
e.g. If you rename `<xs:schema>` to something, say `<foo>`, you will get `<xs:foo>`.

It also depends on where your cursor is during rename:
e.g. If you rename `<ns:tag1>` to `ns:tag2` and your cursor is hovering `ns`, the result will be `<ns:tag2:tag1>`

**Comment by rgrunber** [comment]
I think the part that is confusing for users is the fact that when you activate rename, the proposed text is `ns:foo`. Implicitly, this makes someone assume they are renaming the entire tag name (including namespace). If we want to preserve this behaviour of only renaming the left/right component of the `:`, then we should modify the text that appears in the rename popup.

In other words : `<ns:fo|o>` suggests renaming `foo` & <n|s:foo> suggests renaming `ns`.

@angelozerr does this make sense ?
