### ISSUE TITLE
XSD Closing Tag to Multi-line Element is Justified Fully Left

### ISSUE THREAD

**Issue by Dr-Ogden-Wernstrom** [redhat-developer/vscode-xml#662]
When formatting an XSD while this extension enabled the closing tabs of multiline elements are pulled to column 0.

Eg. 
```
<xs:schema attributeFormDefault="unqualified" elementFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="myType">
    <xs:annotation>
      <xs:documentation>
         Content that spans
         multiple lines.
</xs:documentation>
    </xs:annotation>
  <xs:sequence>
</xs:schema>
```

**Comment by angelozerr** [comment]
Indeed our formatter have some trouble with spaces. We must rewrite this formatter.

**Comment by angelozerr** [comment]
We implemented an experimental formatter 

Here the result with the old formatter (issue that you have filled):

```xml
<xs:schema attributeFormDefault="unqualified" elementFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="myType">
		<xs:annotation>
			<xs:documentation>
         Content that spans
         multiple lines.
</xs:documentation>
		</xs:annotation>
		<xs:sequence>

</xs:schema>
```

Here the result with the experimental formatter:

```xml
<xs:schema attributeFormDefault="unqualified" elementFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="myType">
	<xs:annotation>
		<xs:documentation> Content that spans multiple lines. </xs:documentation>
	</xs:annotation>
	<xs:sequence>
</xs:schema>
```

@JessicaJHee could you write a test with this usecase please.

**Comment by fbricon** [comment]
Any way to keep the documentation on multiple lines here?

**Comment by angelozerr** [comment]
> Any way to keep the documentation on multiple lines here?

According to the rule explained in https://github.com/redhat-developer/vscode-xml/blob/main/docs/Formatting.md#xmlformatexperimental the xs:documentation is a mixed content because this information comes from the XSD grammar (mixed="true")

But I agree with you @fbricon , it should preserve spaces and in this case we must add `xs:documentation` and `xsd:documentation` to the list at:

 * https://github.com/redhat-developer/vscode-xml/blob/738f027a30ae378f4b83a66f02e3755bede2cfc3/package.json#L352
 * https://github.com/eclipse/lemminx/blob/f4d00267bb82221eb3b8d281b616d467940d8d36/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/settings/XMLFormattingOptions.java#L57

The problem with that it will indent correctly the xs:doumentation (because of preserve whitespace).
