### ISSUE TITLE
XML v0.21.2022062916 - Not trusted warning for lemminx-win32.exe

### ISSUE THREAD

**Issue by henrik-jensen** [redhat-developer/vscode-xml#772]
Not trusted warning for lemminx-win32.exe started to appear after install of latest **vscode 1.71.0** and previous version (maybe perhaps earlier?!!!).

Popup Warning:
```
The server binary 
c:\Users\JohnDoe\.vscode\extensions\redhat.vscode-xml-0.21.2022062916-win32-ia32\server\lemminx-win32.exe 
is not trusted. Running the file poses a threat to your system's security. Do you want to add this binary to the
list of trusted binaries and run it?

Source: XML {Extension}
```

vscode and os version (Help->About dialog):
```
Version: 1.71.0 (system setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19043
Sandboxed: No
```
Extension version: **XML 0.21.2022062916**

PS! Warning **does not appear** with pre-release version **XML v0.21.2022090704**

**Edit:**
Forgot this important piece of java info (though I've turned on the `Xml > Server: Prefer Binary` setting. I know,- sometimes, according to the docs, it's ignored). 
```
> java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```
Installed latest java version but problem still remained:
```
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)
```

**Comment by mathmul** [comment]
I am also curious if we can just click "Yes" or is there a real potential security threat?

**Comment by fbricon** [comment]
The warning you see indicates vscode-xml was not able to confirm the integrity of the language server, because it has no sha reference to compare it to. It's not a security threat if you know the binary you installed is embedded with the extension or has been downloaded from Github or the JBoss website.

For old pre-releases, that issue should have been fixed after this [commit](https://github.com/redhat-developer/vscode-xml/commit/b85b5a8267e22a82f34c1b803dfd5988593f59b8).
I confirm the latest pre-release build doesn't have any issue.

**Comment by henrik-jensen** [comment]
@fbricon Thanks for the response. I decided to stay on the prerelease.
Now should I close the issue or wait until a release version with the fix is out?

**Comment by fbricon** [comment]
the fix is out. Nothing left to do

**Comment by rgrunber** [comment]
0.21.0 was already released, https://github.com/redhat-developer/vscode-xml/releases/tag/0.21.0 so the fix should be there. I'll mark this as closed, but feel free to re-open if there is some other issue here.

0.21.2022062916 was a pre-release version of 0.21.0.
0.21.2022090704 was a pre-relase of version 0.21.1, which is under development and not released.

The fact that we bumped from the 0.21.0 release to 0.21.1 (under development) makes it a bit confusing but I don't think there should be an issue.

**Comment by rgrunber** [comment]
The VS Code Markteplace Webpage doesn't distinguish between pre-releases and releases. I think that has more to do with how they render the information.

If I attempt to install another version from the `Uninstall` dropdown, I see all the versions are correct. It's definitely a bug somewhere to see the lack of "pre-release" decorations for it in the UI, but maybe it was some weird state.

![vscode-xml-versions](https://user-images.githubusercontent.com/1417342/189722403-b6d9a818-46b1-4efc-b4b6-801d1a767119.gif)

**Comment by henrik-jensen** [comment]
Ahh I see.
Installed v21.0 that way and now vscode wants me to update to the "buggy" version 0.21.2022062916

![image](https://user-images.githubusercontent.com/9413242/189725197-714e8229-e8c0-48f2-810b-e6e2faec11e2.png)

I think I'll just stay with the pre-release v0.21.2022090704, no problems so far. Thanks for info.

**Comment by rgrunber** [comment]
You're right. It's not some caching issue. This was a bug from when we first introduced pre-relases. It has since been fixed though.

When we first introduced pre-releases, I think we accidentally published a pre-release as a regular release on platforms where we don't support the binary server (eg. win32-ia32 win32-arm64 linux-arm64 linux-armhf alpine-x64 alpine-arm64). I had to use https://marketplace.visualstudio.com/_apis/public/gallery/publishers/redhat/vsextensions/vscode-xml/${version}/vspackage?targetPlatform=${platform} to confirm.

**Comment by vipranarayan14** [comment]
I understand from the conversation here that the issue is fixed. But I am getting this warning message today.

<img width="454" alt="image" src="https://github.com/redhat-developer/vscode-xml/assets/17687018/1ff1ec39-5b4e-4378-ab5b-3dbb1c33cd46">

My VSCode Info:

```
Version: 1.78.1
Commit: 6a995c4f4cc2ced6e3237749973982e751cb0bf9
Date: 2023-05-04T09:57:42.343Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 13_3_1) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.78.1 Chrome/108.0.5359.215 Electron/22.5.1 Safari/537.36
```

**Comment by rgrunber** [comment]
> My VSCode Info:
> 
> ```
> Version: 1.78.1
> Commit: 6a995c4f4cc2ced6e3237749973982e751cb0bf9
> Date: 2023-05-04T09:57:42.343Z
> Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 13_3_1) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.78.1 Chrome/108.0.5359.215 Electron/22.5.1 Safari/537.36
> ```

I'm assuming this isn't run on your local system because the host is MacOS but the extension is for installation on a Linux system. If so that would be the issue.

Judging by the path, it appears to be the universal version that is being used and that should have checksums for each of the binaries that are trusted by default for that release. Are you able to get a terminal into the `/home/vscode/vscode-server/extensions/redhat.vscode-xml-0.25.0/server` folder ? Do you see a `lemminx-linux.sha256` file there (among the `lemminx-osx-x86_64.sha256` & `lemminx-win32.sha256` files   ?

**Comment by bobbynika** [comment]
https://www.virustotal.com/gui/file/ddb40e0762f4805d660523ebfadd3ce1d906bfa0f0c2a18db58fd6d4b30d3498/detection

Matches rule Change PowerShell Policies to an Insecure Level by frack113 at Sigma Integrated Rule Set (GitHub)
Detects use of executionpolicy option to set insecure policies
Matches rule Change PowerShell Policies to an Insecure Level - PowerShell by frack113 at Sigma Integrated Rule Set (GitHub)
Detects use of Set-ExecutionPolicy to set insecure policies
Matches rule Suspicious Get-WmiObject by frack113 at Sigma Integrated Rule Set (GitHub)
The infrastructure for management data and operations that enables local and remote management of Windows personal computers and servers
Matches rule Creation of an Executable by an Executable by frack113 at Sigma Integrated Rule Set (GitHub)
Detects the creation of an executable by another executable
 View rule
 View matches
-
Sigma rule cannot be loaded.
Dynamic Analysis Sandbox Detections
The sandbox Yomi Hunter flags this file as: MALWARE

ddb40e0762f4805d660523ebfadd3ce1d906bfa0f0c2a18db58fd6d4b30d3498


History
Creation Time
2023-07-12 16:36:26 UTC 
First Seen In The Wild
2023-07-12 11:46:49 UTC 
First Submission
2023-07-13 12:04:00 UTC 
Last Submission
2024-01-10 05:13:38 UTC 
Last Analysis
2024-03-27 15:01:15 UTC
Names
lemminx-win32.exe
524730239a99cc519023c7f10574521ad8693d04


Signature info
Signature Verification
File is not signed

**Comment by fbricon** [comment]
the link you provided shows everything's green. 
<img width="1484" alt="Screenshot 2024-04-05 at 12 09 32" src="https://github.com/redhat-developer/vscode-xml/assets/148698/b4ba4348-0e4a-43e8-b37d-a0113029a695">


Whoever flagged it as malware was drunk
