### ISSUE TITLE
Unrecognized VM option 'ExitOnOutOfMemoryError'

### ISSUE THREAD

**Issue by whaynes** [redhat-developer/vscode-xml#966]
While trying to figure out why xml validation wasn't working  I saw this message in the log and thought I should report it.
Version v0.26.1

```
Message: Pending response rejected since connection got disposed
  Code: -32097 
[Trace - 10:41:22 AM] Sending request 'initialize - (0)'.
Unrecognized VM option 'ExitOnOutOfMemoryError'
Did you mean 'OnOutOfMemoryError=<value>'?
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[Error - 10:41:22 AM] Connection to server got closed. Server will not be restarted.
[Error - 10:41:22 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:41:22 AM] XML Support client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:41:22 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by fbricon** [comment]
You may be running with an old Java 8 version.

You can try to either:
-  point [xml.java.home](https://github.com/redhat-developer/vscode-xml/blob/main/docs/Preferences.md#java-home) to a more recent JDK
- set [xml.server.preferBinary](https://github.com/redhat-developer/vscode-xml/blob/main/docs/Preferences.md#server-binary-mode) to `true` to use a graalvm binary instead of the JVM based language server
- add `-XX:+IgnoreUnrecognizedVMOptions` to [xml.server.preferBinary](https://github.com/redhat-developer/vscode-xml/blob/main/docs/Preferences.md#server-binary-mode) to prevent the JVM from crashing

**Comment by whaynes** [comment]
preferBinary fixed the problem. 

Thanks for the quick reply.
